### ISSUE TITLE
Toggle for supplies used between sessions

### ISSUE THREAD

**Issue by Skippyy** [Dyldozer/SuppliesTrackerExternal#28]
I just noticed you added the session saving but I actually liked the old functionality. I found it handy to compare it to the loot I got during that session. Would it be possible to add a toggle in the settings to switch between the two? Thanks in advance, love the plugin!

**Comment by Dyldozer** [comment]
Yeah I was worried that people might like the old way but people sad I was crazy. I'll add it as soon as I get a free min!

**Comment by 808n** [comment]
With the addition to the changelog 1.9, we received session saving - supplies will now save previous sessions.

Give us an option to turn that off. For me, that is counterintuitive of how I think the supplies tracker should work, although a great feature for certain tasks, if the user so wishes.

I want to know how much I've spent over how much I've earned (via loot tracker) per single session while doing a gluttonous boss like Cerberus. I will reset the tab before I log off every night, and sometimes it will continue to store the data. So when I start a new session, I go into the boss not knowing how many supplies I've consumed that trip because it retained the data from the last session by default. It is very easy to forget to check and reset when logging back on the next day. I hope that makes sense.

Thanks for all the hard work you folks do!
-808n


(I know this is re-stating the obvious) (but I loved supplies tracker so much)

**Comment by Dyldozer** [comment]
> With the addition to the changelog 1.9, we received session saving - supplies will now save previous sessions.
> 
> Give us an option to turn that off. For me, that is counterintuitive of how I think the supplies tracker should work, although a great feature for certain tasks, if the user so wishes.
> 
> I want to know how much I've spent over how much I've earned (via loot tracker) per single session while doing a gluttonous boss like Cerberus. I will reset the tab before I log off every night, and sometimes it will continue to store the data. So when I start a new session, I go into the boss not knowing how many supplies I've consumed that trip because it retained the data from the last session by default. It is very easy to forget to check and reset when logging back on the next day. I hope that makes sense.
> 
> Thanks for all the hard work you folks do!
> -808n
> 
> (I know this is re-stating the obvious) (but I loved supplies tracker so much)

Just pull requested it. Its a button to switch between the two I'll add a config option to have one from start but atm I'm too busy with work. Thanks for the feedback glad you like it :)
